/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oekosdb;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.*;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
/*
*   Group 6: Nathalie Y., Nick H., John G.
*/

public class OekosDB_Manager_2 extends javax.swing.JFrame {

    /**
     * Creates new form OekosDB_Manager
     */

    public OekosDB_Manager_2() {
        initComponents();
        updateManagerDB();
        updatePropertyDB();
        
        searchTXT.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = searchTXT.getText();

                if (text.trim().length() == 0) {
                    updateManagerDB();
                    updatePropertyDB();
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = searchTXT.getText();

                if (text.trim().length() == 0) {
                    updateManagerDB();
                    updatePropertyDB();
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                String text = searchTXT.getText();

                if (text.trim().length() == 0) {
                    updateManagerDB();
                    updatePropertyDB();
                }
            }
        
        });            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //Functions
        final String ID = "nyap1";
        final String PW = "COSC*i4fwc";
        final String SERVER = "jdbc:mysql://triton.towson.edu:3360/?serverTimezone=EST#/nyap1db";
    public void updateManagerDB(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
        }catch (ClassNotFoundException e){
            System.out.println(e);
        }

        
        int q;
        
        try {
            Connection con = DriverManager.getConnection(SERVER, ID, PW);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM nyap1db.Manager");

            ResultSetMetaData stdata = rs.getMetaData();
            
            q = stdata.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)man_jTable.getModel();
                    RecordTable.setRowCount(0);
            
            while(rs.next()){
                Vector columnData = new Vector();
                
                for (int i = 0; i <= q; i++ ){
                    columnData.add(rs.getString("managerID"));
                    columnData.add(rs.getString("managerFName"));
                    columnData.add(rs.getString("managerLName"));
                    columnData.add(rs.getString("managerAddress"));
                    columnData.add(rs.getString("managerPhone"));
                }
                RecordTable.addRow(columnData);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//end of update manager
    
    public void updatePropertyDB(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
        }catch (ClassNotFoundException e){
            System.out.println(e);
        }

        
        int q;
        
        try {
            Connection con = DriverManager.getConnection(SERVER, ID, PW);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM nyap1db.Property");

            ResultSetMetaData stdata = rs.getMetaData();
            
            q = stdata.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)man_jTable.getModel();
                    RecordTable.setRowCount(0);
            
            while(rs.next()){
                Vector columnData = new Vector();
                
                for (int i = 0; i <= q; i++ ){
                    columnData.add(rs.getString("propertyID"));
                    columnData.add(rs.getString("propName"));
                    columnData.add(rs.getString("propAddress"));
                    //columnData.add(rs.getString("manID"));        //FOREIGN KEYS
                    //columnData.add(rs.getString("landID"));      

                }
                RecordTable.addRow(columnData);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//end of property manager
    
    //end of Functions
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        manager_jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        man_jTable = new javax.swing.JTable();
        idTXT = new javax.swing.JTextField();
        fnameTXT = new javax.swing.JTextField();
        addressTXT = new javax.swing.JTextField();
        numberTXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lnameTXT = new javax.swing.JTextField();
        searchTXT = new javax.swing.JTextField();
        searchBTN = new javax.swing.JButton();
        searchComboBox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addBTN = new javax.swing.JButton();
        updateBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        propBTN = new javax.swing.JButton();
        leaseBTN = new javax.swing.JButton();
        invoiceBTN = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        property_jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        prop_jTable = new javax.swing.JTable();
        propertyIDTXT = new javax.swing.JTextField();
        propertyNameTXT = new javax.swing.JTextField();
        propertyAddressTXT = new javax.swing.JTextField();
        landlordIDTXT = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        searchTXT2 = new javax.swing.JTextField();
        searchBTN2 = new javax.swing.JButton();
        searchComboBox2 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        managerIDTXT = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        addBTN1 = new javax.swing.JButton();
        updateBTN1 = new javax.swing.JButton();
        deleteBTN1 = new javax.swing.JButton();
        clearBTN1 = new javax.swing.JButton();
        exitBTN1 = new javax.swing.JButton();
        propBTN1 = new javax.swing.JButton();
        leaseBTN1 = new javax.swing.JButton();
        invoiceBTN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manager_jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        manager_jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Last Name:");
        manager_jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 54, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Address:");
        manager_jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 86, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Manager ID:");
        manager_jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Phone Number:");
        manager_jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 118, -1, -1));

        man_jTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        man_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "managerID", "First Name", "Last Name", "Address", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        man_jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                man_jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(man_jTable);
        if (man_jTable.getColumnModel().getColumnCount() > 0) {
            man_jTable.getColumnModel().getColumn(2).setHeaderValue("Last Name");
            man_jTable.getColumnModel().getColumn(4).setHeaderValue("Phone");
        }

        manager_jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 156, 544, 250));

        idTXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTXTActionPerformed(evt);
            }
        });
        manager_jPanel4.add(idTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 21, 431, -1));

        fnameTXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fnameTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        manager_jPanel4.add(fnameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 53, 158, -1));

        addressTXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addressTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        manager_jPanel4.add(addressTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 85, 431, -1));

        numberTXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numberTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numberTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTXTActionPerformed(evt);
            }
        });
        manager_jPanel4.add(numberTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 117, 431, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("First Name:");
        manager_jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 54, -1, -1));

        lnameTXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lnameTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        manager_jPanel4.add(lnameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 53, 187, -1));

        searchTXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTXTActionPerformed(evt);
            }
        });
        manager_jPanel4.add(searchTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 350, -1));

        searchBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });
        manager_jPanel4.add(searchBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        searchComboBox.setFont(new java.awt.Font("Tahoma", 0, 12));
        searchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "First Name", "Last Name", "Address", "Phone" }));
        manager_jPanel4.add(searchComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 410, 100, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("Oekos Database (Manager)");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        addBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        updateBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateBTN.setText("Update");
        updateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTNActionPerformed(evt);
            }
        });

        deleteBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        clearBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clearBTN.setText("Clear");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        exitBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        propBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        propBTN.setText("Properties");
        propBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propBTNActionPerformed(evt);
            }
        });

        leaseBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        leaseBTN.setText("Leases");
        leaseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaseBTNActionPerformed(evt);
            }
        });

        invoiceBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        invoiceBTN.setText("Invoices");
        invoiceBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leaseBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(invoiceBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(propBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(leaseBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(invoiceBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(manager_jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manager_jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Manager", jPanel1);

        property_jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        property_jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Property Address:");
        property_jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 86, 180, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Property ID:");
        property_jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Landlord ID:");
        property_jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        prop_jTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        prop_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Property ID", "Property Name", "Property Address", "manID", "landID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        prop_jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prop_jTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(prop_jTable);

        property_jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 156, 544, 250));

        propertyIDTXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        propertyIDTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        propertyIDTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertyIDTXTActionPerformed(evt);
            }
        });
        property_jPanel5.add(propertyIDTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 21, 431, -1));

        propertyNameTXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        propertyNameTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        property_jPanel5.add(propertyNameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 53, 330, 30));

        propertyAddressTXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        propertyAddressTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        property_jPanel5.add(propertyAddressTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 85, 420, 30));

        landlordIDTXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        landlordIDTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        landlordIDTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landlordIDTXTActionPerformed(evt);
            }
        });
        property_jPanel5.add(landlordIDTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 140, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Property Name:");
        property_jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 54, 140, 20));

        searchTXT2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchTXT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTXT2ActionPerformed(evt);
            }
        });
        property_jPanel5.add(searchTXT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 350, -1));

        searchBTN2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchBTN2.setText("Search");
        searchBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTN2ActionPerformed(evt);
            }
        });
        property_jPanel5.add(searchBTN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        searchComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12));
        searchComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "First Name", "Last Name", "Address", "Phone" }));
        property_jPanel5.add(searchComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 410, 100, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Manager ID:");
        property_jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        managerIDTXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        managerIDTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        managerIDTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerIDTXTActionPerformed(evt);
            }
        });
        property_jPanel5.add(managerIDTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 117, 140, 20));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel17.setText("Oekos Database (Property)");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 60));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        addBTN1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addBTN1.setText("Add");
        addBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTN1ActionPerformed(evt);
            }
        });

        updateBTN1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateBTN1.setText("Update");
        updateBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTN1ActionPerformed(evt);
            }
        });

        deleteBTN1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteBTN1.setText("Delete");
        deleteBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTN1ActionPerformed(evt);
            }
        });

        clearBTN1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clearBTN1.setText("Clear");
        clearBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTN1ActionPerformed(evt);
            }
        });

        exitBTN1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitBTN1.setText("Exit");
        exitBTN1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTN1ActionPerformed(evt);
            }
        });

        propBTN1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        propBTN1.setText("Properties");
        propBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propBTN1ActionPerformed(evt);
            }
        });

        leaseBTN1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        leaseBTN1.setText("Leases");
        leaseBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaseBTN1ActionPerformed(evt);
            }
        });

        invoiceBTN1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        invoiceBTN1.setText("Invoices");
        invoiceBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBTN1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leaseBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(invoiceBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(propBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(leaseBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(invoiceBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(exitBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(property_jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(150, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(94, Short.MAX_VALUE)
                    .addComponent(property_jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Property", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 810, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

               
    JFrame frame; 
    
    private void numberTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTXTActionPerformed

    private void idTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTXTActionPerformed

    private void man_jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_man_jTableMouseClicked

        DefaultTableModel RecordTable = (DefaultTableModel)man_jTable.getModel();
        int selectedRow = man_jTable.getSelectedRow();

        //populate form with the data from the selected row
        idTXT.setText(RecordTable.getValueAt(selectedRow, 0).toString());
        fnameTXT.setText(RecordTable.getValueAt(selectedRow, 1).toString());
        lnameTXT.setText(RecordTable.getValueAt(selectedRow, 2).toString());
        addressTXT.setText(RecordTable.getValueAt(selectedRow, 3).toString());
        numberTXT.setText(RecordTable.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_man_jTableMouseClicked

    private void searchTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTXTActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
        searchTXT.getText();
        try {
            Connection con = DriverManager.getConnection(SERVER, ID, PW);
            PreparedStatement pstmt;
            ResultSet rs;
            ResultSetMetaData stdata;
            DefaultTableModel RecordTable = (DefaultTableModel)man_jTable.getModel();
            int q;
            
            //"First Name", "Last Name", "Address", "Phone"
            switch(searchComboBox.getSelectedItem().toString()){
                case "ID":
                    pstmt = con.prepareStatement("SELECT * FROM nyap1db.Manager "
                    +"WHERE managerID = ?");
                    pstmt.setString(1, searchTXT.getText());
                    rs = pstmt.executeQuery();
                    stdata = rs.getMetaData();
                    RecordTable.setRowCount(0);
                    q = stdata.getColumnCount();

                    while(rs.next()){
                        Vector columnData = new Vector();

                        for (int i = 0; i <= q; i++ ){
                            columnData.add(rs.getString("managerID"));
                            columnData.add(rs.getString("managerFName"));
                            columnData.add(rs.getString("managerLName"));
                            columnData.add(rs.getString("managerAddress"));
                            columnData.add(rs.getString("managerPhone"));
                        }
                        RecordTable.addRow(columnData);
                    }
                    break;
                case "First Name":
                    pstmt = con.prepareStatement("SELECT * FROM nyap1db.Manager "
                    +"WHERE managerFName LIKE ?");
                    pstmt.setString(1, "%" + searchTXT.getText() + "%");
                    rs = pstmt.executeQuery();
                    stdata = rs.getMetaData();
                    RecordTable.setRowCount(0);
                    q = stdata.getColumnCount();

                    while(rs.next()){
                        Vector columnData = new Vector();

                        for (int i = 0; i <= q; i++ ){
                            columnData.add(rs.getString("managerID"));
                            columnData.add(rs.getString("managerFName"));
                            columnData.add(rs.getString("managerLName"));
                            columnData.add(rs.getString("managerAddress"));
                            columnData.add(rs.getString("managerPhone"));
                        }
                        RecordTable.addRow(columnData);
                    }
                    break;
                case "Last Name":
                    pstmt = con.prepareStatement("SELECT * FROM nyap1db.Manager "
                    +"WHERE managerLName LIKE ?");
                    pstmt.setString(1, "%" + searchTXT.getText() + "%");
                    rs = pstmt.executeQuery();
                    stdata = rs.getMetaData();
                    RecordTable.setRowCount(0);
                    q = stdata.getColumnCount();

                    while(rs.next()){
                        Vector columnData = new Vector();

                        for (int i = 0; i <= q; i++ ){
                            columnData.add(rs.getString("managerID"));
                            columnData.add(rs.getString("managerFName"));
                            columnData.add(rs.getString("managerLName"));
                            columnData.add(rs.getString("managerAddress"));
                            columnData.add(rs.getString("managerPhone"));
                        }
                        RecordTable.addRow(columnData);
                    }
                    break;
                case "Address":
                    pstmt = con.prepareStatement("SELECT * FROM nyap1db.Manager "
                    +"WHERE managerAddress LIKE ?");
                    pstmt.setString(1, "%" + searchTXT.getText() + "%");
                    rs = pstmt.executeQuery();
                    stdata = rs.getMetaData();
                    RecordTable.setRowCount(0);
                    q = stdata.getColumnCount();

                    while(rs.next()){
                        Vector columnData = new Vector();

                        for (int i = 0; i <= q; i++ ){
                            columnData.add(rs.getString("managerID"));
                            columnData.add(rs.getString("managerFName"));
                            columnData.add(rs.getString("managerLName"));
                            columnData.add(rs.getString("managerAddress"));
                            columnData.add(rs.getString("managerPhone"));
                        }
                        RecordTable.addRow(columnData);
                    }
                    break;
                case "Phone":
                    pstmt = con.prepareStatement("SELECT * FROM nyap1db.Manager "
                    +"WHERE managerPhone LIKE ?");
                    pstmt.setString(1, "%" + searchTXT.getText() + "%");
                    rs = pstmt.executeQuery();
                    stdata = rs.getMetaData();
                    q = stdata.getColumnCount();
            
                    RecordTable.setRowCount(0);

                    while(rs.next()){
                        Vector columnData = new Vector();

                        for (int i = 0; i <= q; i++ ){
                            columnData.add(rs.getString("managerID"));
                            columnData.add(rs.getString("managerFName"));
                            columnData.add(rs.getString("managerLName"));
                            columnData.add(rs.getString("managerAddress"));
                            columnData.add(rs.getString("managerPhone"));
                        }
                        RecordTable.addRow(columnData);
                    }
                    break;
            }
            
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchBTNActionPerformed

    private void prop_jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prop_jTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)prop_jTable.getModel();
        int selectedRow = prop_jTable.getSelectedRow();

        //populate form with the data from the selected row
        propertyIDTXT.setText(RecordTable.getValueAt(selectedRow, 0).toString());
        propertyNameTXT.setText(RecordTable.getValueAt(selectedRow, 1).toString());
        propertyAddressTXT.setText(RecordTable.getValueAt(selectedRow, 2).toString());
        managerIDTXT.setText(RecordTable.getValueAt(selectedRow, 3).toString());
        landlordIDTXT.setText(RecordTable.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_prop_jTableMouseClicked

    private void propertyIDTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertyIDTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propertyIDTXTActionPerformed

    private void landlordIDTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landlordIDTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landlordIDTXTActionPerformed

    private void searchTXT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTXT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTXT2ActionPerformed

    private void searchBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTN2ActionPerformed
        // TODO add your handling code here:
        searchTXT.getText();
        try {
            Connection con = DriverManager.getConnection(SERVER, ID, PW);
            PreparedStatement pstmt;
            ResultSet rs;
            ResultSetMetaData stdata;
            DefaultTableModel RecordTable = (DefaultTableModel)prop_jTable.getModel();
            int q;
            
            //"Property ID", "propertyName","propertyAddress", "managerID", "landlordID"
            switch(searchComboBox.getSelectedItem().toString()){
                case "ID":
                    pstmt = con.prepareStatement("SELECT * FROM nyap1db.Property "
                    +"WHERE propertyID = ?");
                    pstmt.setString(1, searchTXT.getText());
                    rs = pstmt.executeQuery();
                    stdata = rs.getMetaData();
                    RecordTable.setRowCount(0);
                    q = stdata.getColumnCount();

                    while(rs.next()){
                        Vector columnData = new Vector();

                        for (int i = 0; i <= q; i++ ){
                            columnData.add(rs.getString("propertyID"));
                            columnData.add(rs.getString("propName"));
                            columnData.add(rs.getString("propAddress"));
                            columnData.add(rs.getString("managerID"));  
                            columnData.add(rs.getString("landlordID"));
                        }
                        RecordTable.addRow(columnData);
                    }
                    break;
                case "Property Name":
                    pstmt = con.prepareStatement("SELECT * FROM nyap1db.Property "
                    +"WHERE propName LIKE ?");
                    pstmt.setString(1, "%" + searchTXT.getText() + "%");
                    rs = pstmt.executeQuery();
                    stdata = rs.getMetaData();
                    RecordTable.setRowCount(0);
                    q = stdata.getColumnCount();

                    while(rs.next()){
                        Vector columnData = new Vector();

                        for (int i = 0; i <= q; i++ ){
                            columnData.add(rs.getString("propertyID"));
                            columnData.add(rs.getString("propName"));
                            columnData.add(rs.getString("propAddress"));
                            columnData.add(rs.getString("managerID"));  // FOREIGN KEYS
                            columnData.add(rs.getString("landlordID"));
                        }
                        RecordTable.addRow(columnData);
                    }
                    break;
                case "property Address":
                    pstmt = con.prepareStatement("SELECT * FROM nyap1db.Property "
                    +"WHERE propertyAddress LIKE ?");
                    pstmt.setString(1, "%" + searchTXT.getText() + "%");
                    rs = pstmt.executeQuery();
                    stdata = rs.getMetaData();
                    RecordTable.setRowCount(0);
                    q = stdata.getColumnCount();

                    while(rs.next()){
                        Vector columnData = new Vector();

                        for (int i = 0; i <= q; i++ ){
                            columnData.add(rs.getString("propertyID"));
                            columnData.add(rs.getString("propName"));
                            columnData.add(rs.getString("propAddress"));
                            columnData.add(rs.getString("managerID"));  // FOREIGN KEYS
                            columnData.add(rs.getString("landlordID"));
                        }
                        RecordTable.addRow(columnData);
                    }
                    break;
                case "manager ID":
                    pstmt = con.prepareStatement("SELECT * FROM nyap1db.Property "
                    +"WHERE manID LIKE ?");
                    pstmt.setString(1, "%" + searchTXT.getText() + "%");
                    rs = pstmt.executeQuery();
                    stdata = rs.getMetaData();
                    RecordTable.setRowCount(0);
                    q = stdata.getColumnCount();

                    while(rs.next()){
                        Vector columnData = new Vector();

                        for (int i = 0; i <= q; i++ ){
                            columnData.add(rs.getString("propertyID"));
                            columnData.add(rs.getString("propName"));
                            columnData.add(rs.getString("propAddress"));
                            columnData.add(rs.getString("managerID"));  // FOREIGN KEYS
                            columnData.add(rs.getString("landlordID"));
                        }
                        RecordTable.addRow(columnData);
                    }
                    break;
                case "landlord ID":
                    pstmt = con.prepareStatement("SELECT * FROM nyap1db.Property "
                    +"WHERE landID LIKE ?");
                    pstmt.setString(1, "%" + searchTXT.getText() + "%");
                    rs = pstmt.executeQuery();
                    stdata = rs.getMetaData();
                    RecordTable.setRowCount(0);
                    q = stdata.getColumnCount();

                    while(rs.next()){
                        Vector columnData = new Vector();

                        for (int i = 0; i <= q; i++ ){
                            columnData.add(rs.getString("propertyID"));
                            columnData.add(rs.getString("propName"));
                            columnData.add(rs.getString("propAddress"));
                            columnData.add(rs.getString("managerID"));  // FOREIGN KEYS
                            columnData.add(rs.getString("landlordID"));
                        }
                        RecordTable.addRow(columnData);
                    }
                    break;
            }
            
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchBTN2ActionPerformed

    private void managerIDTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerIDTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managerIDTXTActionPerformed

    private void invoiceBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceBTNActionPerformed
        // TODO add the rest of the table attributes
        JFrame invoiceFrame = new JFrame("Invoices");
        invoiceFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        JScrollPane jScrollPane4 = new javax.swing.JScrollPane();

        invoiceTable = new javax.swing.JTable();
        invoiceTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        invoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] { //add "landlordID", "suiteID", "venID"
                "Invoice No.", "Due Date", "Expense Period", "Total Amount", "Amount Paid"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        try {
            Connection con = DriverManager.getConnection(SERVER, ID, PW);
            Statement stmt = con.createStatement();
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM nyap1db.Invoice WHERE manID = ?");

            pstmt.setString(1, idTXT.getText()); //gets the managerID from the textbox

            ResultSet rs = pstmt.executeQuery();
            ResultSetMetaData stdata = rs.getMetaData();

            int q = stdata.getColumnCount();

            DefaultTableModel RecordTable = (DefaultTableModel)propTable.getModel();
            RecordTable.setRowCount(0);

            while(rs.next()){
                Vector columnData = new Vector();

                for (int i = 0; i <= q; i++ ){
                    columnData.add(rs.getString("invoiceNo"));
                    columnData.add(rs.getString("due_date"));
                    columnData.add(rs.getString("expense_period"));
                    columnData.add(rs.getString("total_amount"));
                    columnData.add(rs.getString("amount_paid"));
                }
                RecordTable.addRow(columnData);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        jScrollPane4.setViewportView(propTable);
        invoiceFrame.getContentPane().add(jScrollPane4, BorderLayout.CENTER);
        invoiceFrame.pack();
        invoiceFrame.setVisible(true);
    }//GEN-LAST:event_invoiceBTNActionPerformed

    private void leaseBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaseBTNActionPerformed
        // TODO add the rest of the table information
        JFrame leaseFrame = new JFrame("Leases");
        leaseFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        JScrollPane jScrollPane3 = new javax.swing.JScrollPane();

        leaseTable = new javax.swing.JTable();
        leaseTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        leaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] { //add "landlordID", "suiteID", "venID"
                "leaseID", "Occupancy Status", "Start Date", "End Date", "propertyID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        try {
            Connection con = DriverManager.getConnection(SERVER, ID, PW);
            Statement stmt = con.createStatement();
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM nyap1db.Lease WHERE manID = ?");

            pstmt.setString(1, idTXT.getText()); //gets the managerID from the textbox

            ResultSet rs = pstmt.executeQuery();
            ResultSetMetaData stdata = rs.getMetaData();

            int q = stdata.getColumnCount();

            DefaultTableModel RecordTable = (DefaultTableModel)propTable.getModel();
            RecordTable.setRowCount(0);

            while(rs.next()){
                Vector columnData = new Vector();

                for (int i = 0; i <= q; i++ ){
                    columnData.add(rs.getString("leaseID"));
                    columnData.add(rs.getString("occupancy_status"));
                    columnData.add(rs.getString("start_date"));
                    columnData.add(rs.getString("expiration_date"));
                    columnData.add(rs.getString("propID"));
                }
                RecordTable.addRow(columnData);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        jScrollPane3.setViewportView(propTable);
        leaseFrame.getContentPane().add(jScrollPane3, BorderLayout.CENTER);
        leaseFrame.pack();
        leaseFrame.setVisible(true);
    }//GEN-LAST:event_leaseBTNActionPerformed

    private void propBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propBTNActionPerformed
        // Window pops up with table that displays properties handled by a particular manager
        JFrame propFrame = new JFrame("Properties");
        propFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        JScrollPane jScrollPane2 = new javax.swing.JScrollPane();

        propTable = new javax.swing.JTable();
        propTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        propTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] { //add "landlordID"
                "propertyID", "Name", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        try {
            Connection con = DriverManager.getConnection(SERVER, ID, PW);
            Statement stmt = con.createStatement();
            PreparedStatement pstmt = con.prepareStatement("SELECT * FROM nyap1db.Property WHERE manID = ?");

            pstmt.setString(1, idTXT.getText());
            ResultSet rs = pstmt.executeQuery();
            ResultSetMetaData stdata = rs.getMetaData();

            int q = stdata.getColumnCount();

            DefaultTableModel RecordTable = (DefaultTableModel)propTable.getModel();
            RecordTable.setRowCount(0);

            while(rs.next()){
                Vector columnData = new Vector();

                for (int i = 0; i <= q; i++ ){
                    columnData.add(rs.getString("propertyID"));
                    columnData.add(rs.getString("propName"));
                    columnData.add(rs.getString("propAddress"));
                    //columnData.add(rs.getString("landID"));
                }
                RecordTable.addRow(columnData);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        jScrollPane2.setViewportView(propTable);
        propFrame.getContentPane().add(jScrollPane2, BorderLayout.CENTER);
        propFrame.pack();
        propFrame.setVisible(true);

    }//GEN-LAST:event_propBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit?", "OekosDB",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_exitBTNActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // TODO add your handling code here:
        idTXT.setText("");
        fnameTXT.setText("");
        lnameTXT.setText("");
        addressTXT.setText("");
        numberTXT.setText("");
    }//GEN-LAST:event_clearBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)man_jTable.getModel();
        int SelectedRow = man_jTable.getSelectedRow();

        try{
            int id = Integer.parseInt(RecordTable.getValueAt(SelectedRow, 0).toString());

            //warning before delete pop-up
            frame = new JFrame("Delete");

            if(JOptionPane.showConfirmDialog(frame, "Are you sure you want"
                + " to delete this entry?", "WARNING", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){

            Connection con = DriverManager.getConnection(SERVER, ID, PW);

            PreparedStatement pstmt = con.prepareStatement("DELETE from nyap1db.Manager "
                +"WHERE managerID = ?");

            pstmt.setString(1, idTXT.getText());

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Manager Deleted");

            updateManagerDB();
            //clears the text fields
            idTXT.setText("");
            fnameTXT.setText("");
            lnameTXT.setText("");
            addressTXT.setText("");
            numberTXT.setText("");
        }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_deleteBTNActionPerformed

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTNActionPerformed
        // TODO: figure out how to update managerID
        try {
            Connection con = DriverManager.getConnection(SERVER, ID, PW);
            PreparedStatement pstmt = con.prepareStatement("UPDATE nyap1db.Manager "
                +"SET managerFName = ?, managerLName = ?, "
                +"managerAddress = ?, managerPhone = ? WHERE managerID = ?");

            pstmt.setString(1, fnameTXT.getText());
            pstmt.setString(2, lnameTXT.getText());
            pstmt.setString(3, addressTXT.getText());
            pstmt.setString(4, numberTXT.getText());
            pstmt.setString(5, idTXT.getText());

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Manager Updated");
            updateManagerDB();

        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed

        try {
            Connection con = DriverManager.getConnection(SERVER, ID, PW);
            PreparedStatement pstmt = con.prepareStatement("INSERT INTO nyap1db.Manager"
                +" (managerID, managerFName, managerLName, managerAddress, managerPhone) "
                +"VALUES (?, ?, ?, ?, ?)");

            pstmt.setString(1, idTXT.getText());
            pstmt.setString(2, fnameTXT.getText());
            pstmt.setString(3, lnameTXT.getText());
            pstmt.setString(4, addressTXT.getText());
            pstmt.setString(5, numberTXT.getText());

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Manager Added");
            updateManagerDB();

        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addBTNActionPerformed

    //      *****************************************                           
    //      **************** PROPERTY ***************
    
    private void addBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTN1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection(SERVER, ID, PW);
            PreparedStatement pstmt = con.prepareStatement("INSERT INTO nyap1db.Property"
                +" (propertyID, propertyName, propertyAddress, managerID, landlordID) "
                +"VALUES (?, ?, ?, ?, ?)");

            pstmt.setString(1, propertyIDTXT.getText());
            pstmt.setString(2, propertyNameTXT.getText());
            pstmt.setString(3, propertyAddressTXT.getText());
            pstmt.setString(4, managerIDTXT.getText());
            pstmt.setString(5, landlordIDTXT.getText());

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Property Added");
            updateManagerDB();

        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addBTN1ActionPerformed

    private void updateBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTN1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection(SERVER, ID, PW);
            PreparedStatement pstmt = con.prepareStatement("UPDATE nyap1db.Property "
                +"SET propertyID = ?, propertyName = ?, "
                +"propertyAddress = ?, managerID = ? WHERE landlordID = ?");

            pstmt.setString(1, propertyIDTXT.getText());
            pstmt.setString(2, propertyNameTXT.getText());
            pstmt.setString(3, propertyAddressTXT.getText());
            pstmt.setString(4, managerIDTXT.getText());
            pstmt.setString(5, landlordIDTXT.getText());

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Property Updated");
            updateManagerDB();

        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateBTN1ActionPerformed

    private void deleteBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTN1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)prop_jTable.getModel();
        int SelectedRow = prop_jTable.getSelectedRow();

        try{
            int id = Integer.parseInt(RecordTable.getValueAt(SelectedRow, 0).toString());

            //warning before delete pop-up
            frame = new JFrame("Delete");

            if(JOptionPane.showConfirmDialog(frame, "Are you sure you want"
                + " to delete this entry?", "WARNING", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){

            Connection con = DriverManager.getConnection(SERVER, ID, PW);

            PreparedStatement pstmt = con.prepareStatement("DELETE from nyap1db.Property "
                +"WHERE propertyID = ?");

            pstmt.setString(1, idTXT.getText());

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Property Deleted");

            updatePropertyDB();
            //clears the text fields
            propertyIDTXT.setText("");
            propertyNameTXT.setText("");
            propertyAddressTXT.setText("");
            managerIDTXT.setText("");
            landlordIDTXT.setText("");
        }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_deleteBTN1ActionPerformed

    private void clearBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTN1ActionPerformed
        // TODO add your handling code here:
        propertyIDTXT.setText("");
        propertyNameTXT.setText("");
        propertyAddressTXT.setText("");
        managerIDTXT.setText("");
        landlordIDTXT.setText("");
    }//GEN-LAST:event_clearBTN1ActionPerformed

    private void exitBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTN1ActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit?", "OekosDB",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_exitBTN1ActionPerformed

    private void propBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propBTN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propBTN1ActionPerformed

    private void leaseBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaseBTN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leaseBTN1ActionPerformed

    private void invoiceBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceBTN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceBTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OekosDB_Manager_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OekosDB_Manager_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OekosDB_Manager_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OekosDB_Manager_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OekosDB_Manager_2().setVisible(true);
            }
        });
        
    }
    private javax.swing.JTable propTable;
    private javax.swing.JTable leaseTable;
    private javax.swing.JTable invoiceTable;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JButton addBTN1;
    private javax.swing.JTextField addressTXT;
    private javax.swing.JButton clearBTN;
    private javax.swing.JButton clearBTN1;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton deleteBTN1;
    private javax.swing.JButton exitBTN;
    private javax.swing.JButton exitBTN1;
    private javax.swing.JTextField fnameTXT;
    private javax.swing.JTextField idTXT;
    private javax.swing.JButton invoiceBTN;
    private javax.swing.JButton invoiceBTN1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField landlordIDTXT;
    private javax.swing.JButton leaseBTN;
    private javax.swing.JButton leaseBTN1;
    private javax.swing.JTextField lnameTXT;
    private javax.swing.JTable man_jTable;
    private javax.swing.JTextField managerIDTXT;
    private javax.swing.JPanel manager_jPanel4;
    private javax.swing.JTextField numberTXT;
    private javax.swing.JButton propBTN;
    private javax.swing.JButton propBTN1;
    private javax.swing.JTable prop_jTable;
    private javax.swing.JTextField propertyAddressTXT;
    private javax.swing.JTextField propertyIDTXT;
    private javax.swing.JTextField propertyNameTXT;
    private javax.swing.JPanel property_jPanel5;
    private javax.swing.JButton searchBTN;
    private javax.swing.JButton searchBTN2;
    private javax.swing.JComboBox<String> searchComboBox;
    private javax.swing.JComboBox<String> searchComboBox2;
    private javax.swing.JTextField searchTXT;
    private javax.swing.JTextField searchTXT2;
    private javax.swing.JButton updateBTN;
    private javax.swing.JButton updateBTN1;
    // End of variables declaration//GEN-END:variables
}

